name: 'Block PR Merges if Keyword Found'
description: "Checks that the added code in a PR doesn't contain a keyword"
author: 'itsvs'
branding:
  icon: 'git-pull-request'
  color: 'gray-dark'
inputs:
  github-token:
    description: 'Github token, added magically'
  keyword:
    description: 'Word that must not be contained in the PR code'
    
runs:
  using: 'node12'
  main: 'lib/main.js'